name: Check OpenAPI Spec > Data API

on:
  pull_request:
    paths:
      - "source/openapi-data-api-v1/**"
      - "source/data-api/openapi.txt"

env:
  SPEC_DIRECTORY: "source/openapi-data-api-v1"
  BUNDLED_SPEC_FILENAME: "bundled.yaml"

jobs:
  check-openapi-spec-data-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Verify Bundled OpenAPI File Hash
        working-directory: ${{ env.SPEC_DIRECTORY }}
        run: |
          npx -y @redocly/cli@latest bundle openapi.yaml --output=latest-bundled.yaml
          expected_hash=$(md5sum latest-bundled.yaml | awk '{ print $1 }')
          provided_hash=$(md5sum ${{ env.BUNDLED_SPEC_FILENAME }} | awk '{ print $1 }')
          echo "expected_hash $expected_hash"
          echo "provided_hash $provided_hash"
          if [ "$provided_hash" != "$expected_hash" ]; then
            echo "The bundled OpenAPI definition does not match the source files. Did you forget to regenerate the bundled spec?"
            echo "Bundled File: ${{ env.SPEC_DIRECTORY }}/${{ env.BUNDLED_SPEC_FILENAME }} (Hash: $provided_hash)"
            echo "Source File: ${{ env.SPEC_DIRECTORY }}/openapi.yaml (Bundled hash: $expected_hash)"
            echo "To regenerate the spec, run this command from the repo root:"
            echo ""
            echo "    npx @redocly/cli@latest bundle ${{ env.SPEC_DIRECTORY }}/openapi.yaml --output=${{ env.SPEC_DIRECTORY }}/${{ env.BUNDLED_SPEC_FILENAME }}"
            echo ""
            exit 1
          fi
      - name: Validate OpenAPI Spec
        run: |
          npx -y @redocly/cli@latest lint ${{ env.SPEC_DIRECTORY }}/${{ env.BUNDLED_SPEC_FILENAME }} --config redocly.yaml
